### ISSUE TITLE
Feature: using docker to run the code

### ISSUE THREAD

**Issue by modaresimr** [roborescue/rcrs-adf-sample#12]
I think it can be interesting to use docker and gradle alpine image (gradle:jdk17-alpine ~~or openjdk:17-jdk-alpine~~)
In this case, it can be easier for some newcomers to start using the ADF and also the simulator.

each time they can easily run the code by 
```docker-compose up```

**Comment by gnardin** [comment]
@modaresimr 
Can you please specify where this setting should be included?
Thank you,

**Comment by modaresimr** [comment]
@duplicated: https://github.com/roborescue/rcrs-server/issues/55#issue-1067595957
