### ISSUE TITLE
map change problem

### ISSUE THREAD

**Issue by 2661348402** [roborescue/rcrs-adf-sample#18]
When I try to change a map, he keeps getting the following error
![图片](https://user-images.githubusercontent.com/80761477/163197210-4aa36eba-40cd-4423-a529-3d1f47de60c6.png)

And i tried launch --debug, but I don't know how to use it. Is there any documentation about debug?
@gnardin

**Comment by gnardin** [comment]
@2661348402 
This is not an `adf-sample-agent-java` question, it is a `rcrs-server` question.
Please open another issue in the proper repository.
