### ISSUE TITLE
start.sh error: java.net.URLClassLoader

### ISSUE THREAD

**Issue by swhaKo** [roborescue/rcrs-adf-sample#5]
Dear developer,
As refer to the manual, run rcrs-sever/start-comprun.sh script and when I run **start.sh** script, there is one error so that I cannot run the script.

Here is my java version information.
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

Error message:
[ RCRS ADF Version 2.3.0 (build 20180327T191931Z) ]

Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at adf.launcher.AgentLauncher.initConnector(AgentLauncher.java:56)
	at adf.launcher.AgentLauncher.init(AgentLauncher.java:35)
	at adf.launcher.AgentLauncher.<init>(AgentLauncher.java:29)
	at adf.Main.main(Main.java:23)

Would you help fix this running errors?
I would really appreciate it if you could help.

Best regards,
swha

**Comment by gnardin** [comment]
Dear @tkmnet ,
Can you please take a look at this issue as it is related to the [roborescue/rcrs-adf-core Issue-1](https://github.com/roborescue/rcrs-adf-core/issues/1)?
Thank you,
-Luis

**Comment by tkmnet** [comment]
Please merge and build my pull-request on rcrs-adf-core, and update adf-core.jar on this repository.

**Comment by gnardin** [comment]
Dear @tkmnet ,
I merged and tested the fix successfully.
Thank you,

**Comment by gnardin** [comment]
Dear @swhaKo ,
The problem you reported has been fixed. We have tested it and it work correctly.
Please check if you have any issues and let us know.
I will wait until **May 25** or until **you reply** to close the issue.
Best regards,
