### ISSUE TITLE
./compile.sh give errors

### ISSUE THREAD

**Issue by sh974** [roborescue/rcrs-adf-sample#8]
I followed the tutorial and I got compilation errors. I satisfied all of the software requirements and I am currently using Ubuntu 16.04. 

Attached are screenshots of the error messages. 
![error](https://user-images.githubusercontent.com/54999618/76154070-10253b80-60a4-11ea-9a5d-49854492dc3e.png)
![error1](https://user-images.githubusercontent.com/54999618/76154073-12879580-60a4-11ea-962c-681998df4137.png)

**Comment by gnardin** [comment]
Dear @sh974 ,

I could reproduce the same errors. I identified that the `adf-core.jar` file was incomplete. I updated it and it is working properly in my installation now.

Can you please test and inform if the problem has been solved for you?

Kind Regards,

**Comment by sh974** [comment]
I was able to compile without errors -- thank you so much for your quick response!
